version: "3.9"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "10116:10116/udp"
    environment:
      - ENDPOINT=postgres
    external_links:
      - docker_python-postgres-1
    networks:
      - backing-services

networks: 
  backing-services:
    driver: bridge