version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "10116:10116/udp"
    environment:
      - ENDPOINT=postgres
    external_links:
      - envio-firmware-postgres-1
    networks:
      - backing-services

# networks: 
#   backing-services:
#     driver: bridge